import { Order, Product } from "./types";

export const defaultProducts: Product[] = [
  {
    id: "puffer-01",
    name: "Aero Loft Puffer",
    slug: "aero-loft-puffer",
    category: "Outerwear",
    tags: ["winter", "technical", "bestseller"],
    price: 280,
    originalPrice: 320,
    discountPercent: 15,
    stock: 14,
    badge: "New Drop",
    rating: 4.8,
    colors: ["Graphite", "Ice", "Sand"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "Featherweight insulation with a windproof matte shell and sealed seams for winter commutes.",
    highlights: ["Water-repellent shell", "700-fill recycled down", "Hidden phone pocket"],
    images: [
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    id: "hoodie-01",
    name: "Studio Weight Hoodie",
    slug: "studio-weight-hoodie",
    category: "Essentials",
    tags: ["all-season", "lounge", "cotton"],
    price: 120,
    originalPrice: 140,
    discountPercent: 10,
    stock: 32,
    badge: "Editor Pick",
    rating: 4.6,
    colors: ["Slate", "Chalk", "Cypress"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    description: "Structured fleece hoodie with minimalist lines and a brushed interior that drapes cleanly.",
    highlights: ["Pre-shrunk fleece", "No-pill finish", "Heat-taped drawcords"],
    images: [
      "https://images.unsplash.com/photo-1542293787938-4d273c37cbd3?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    id: "sneaker-01",
    name: "Tempo Knit Sneaker",
    slug: "tempo-knit-sneaker",
    category: "Footwear",
    tags: ["lightweight", "daily", "breathable"],
    price: 165,
    originalPrice: 195,
    discountPercent: 15,
    stock: 25,
    badge: "Bestseller",
    rating: 4.9,
    colors: ["Onyx", "Fog", "Alabaster"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    description: "Breathable knit upper with responsive cushioning and a sculpted midsole for all-day wear.",
    highlights: ["Cloud knit upper", "Stabilized heel", "Cushioned EVA midsole"],
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    id: "trench-01",
    name: "Modular Storm Trench",
    slug: "modular-storm-trench",
    category: "Outerwear",
    tags: ["rain", "commuter", "packable"],
    price: 350,
    originalPrice: 410,
    discountPercent: 12,
    stock: 12,
    badge: "Limited",
    rating: 4.7,
    colors: ["Jet", "Stone"],
    sizes: ["S", "M", "L", "XL"],
    description: "3-layer shell with taped seams, detachable hood, and stealth vents built for city weather.",
    highlights: ["10k waterproof", "Armpit vents", "Packable hood"],
    images: [
      "https://images.unsplash.com/photo-1509635022432-0222d6b29763?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    id: "denim-01",
    name: "Selvedge Taper Denim",
    slug: "selvedge-taper-denim",
    category: "Denim",
    tags: ["japan", "raw", "heritage"],
    price: 190,
    originalPrice: 220,
    discountPercent: 14,
    stock: 18,
    badge: "Heritage",
    rating: 4.5,
    colors: ["Indigo"],
    sizes: ["28", "30", "32", "34", "36"],
    description: "13.5oz Japanese selvedge denim with a modern taper and soft rinse for immediate comfort.",
    highlights: ["Chain-stitched hems", "Hidden coin pocket", "Antique brass hardware"],
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    id: "knit-01",
    name: "Merino Rib Mockneck",
    slug: "merino-rib-mockneck",
    category: "Knitwear",
    tags: ["luxury", "merino", "layering"],
    price: 145,
    originalPrice: 165,
    discountPercent: 12,
    stock: 20,
    badge: "Layering",
    rating: 4.4,
    colors: ["Charcoal", "Birch"],
    sizes: ["XS", "S", "M", "L", "XL"],
    description: "Extra-fine merino knit with a clean rib texture and a mock neckline that sits softly.",
    highlights: ["100% merino", "Thermo-regulating", "Non-itch finish"],
    images: [
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    id: "bag-01",
    name: "Transit Weekender",
    slug: "transit-weekender",
    category: "Accessories",
    tags: ["carry", "travel", "waterproof"],
    price: 210,
    originalPrice: 240,
    discountPercent: 13,
    stock: 27,
    badge: "Carry Essential",
    rating: 4.6,
    colors: ["Black", "Dune"],
    sizes: ["OS"],
    description: "Structured weekender with waterproof zips, 16-inch laptop sleeve, and luggage passthrough.",
    highlights: ["900d nylon shell", "Quick-access top", "Trolley sleeve"],
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1600&q=80",
    ],
  },
  {
    id: "tee-01",
    name: "Weightless Pima Tee",
    slug: "weightless-pima-tee",
    category: "Essentials",
    tags: ["pima", "summer", "light"],
    price: 60,
    originalPrice: 75,
    discountPercent: 20,
    stock: 40,
    badge: "Everyday",
    rating: 4.3,
    colors: ["White", "Black", "Drift"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    description: "Airweight Peruvian pima cotton tee with a clean drape and stay-flat collar.",
    highlights: ["Soft touch", "No-shrink collar", "Breathable weave"],
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1600&q=80",
    ],
  },
];

export const defaultOrders: Order[] = [
  {
    id: "ORD-1041",
    items: [
      { productId: "puffer-01", quantity: 1, color: "Graphite", size: "M" },
      { productId: "tee-01", quantity: 2, size: "L", color: "White" },
    ],
    total: 400,
    email: "jane@client.com",
    address: "240 Hudson St, NY",
    status: "paid",
    createdAt: new Date().toISOString(),
    notes: "Deliver evenings only",
  },
  {
    id: "ORD-1048",
    items: [{ productId: "sneaker-01", quantity: 1, size: "10", color: "Onyx" }],
    total: 165,
    email: "studio@artlist.com",
    address: "Remote pickup",
    status: "pending",
    createdAt: new Date().toISOString(),
    notes: "Gift wrap",
  },
];
